Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots()

emph_color = (0.95, 0.05, 0.05)
sec_color = [(0.05, 0.05+0.075*x, 0.95) for x in range(4)]
df["Japan"].plot(ax=ax, legend=True, color=emph_color, linewidth=2.5)
df["United Kingdom"].plot(ax=ax, legend=True, color=sec_color[0], alpha=0.4, linewidth=0.75)
df["United States"].plot(ax=ax, legend=True, color=sec_color[1], alpha=0.4, linewidth=0.75)
df["China"].plot(ax=ax, legend=True, color=sec_color[2], alpha=0.4, linewidth=0.75)
df["India"].plot(ax=ax, legend=True, color=sec_color[3], alpha=0.4, linewidth=0.75)

ax.spines["right"].set_visible(False)
ax.spines["top"].set_visible(False)
ax.set_title("Japan's Aging Population")
ax.set_ylabel("Age Dependency Ratio")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[37], line 6[0m
[1;32m      4[0m sec_color [38;5;241m=[39m [([38;5;241m0.05[39m, [38;5;241m0.05[39m[38;5;241m+[39m[38;5;241m0.075[39m[38;5;241m*[39mx, [38;5;241m0.95[39m) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m4[39m)]
[1;32m      5[0m df[[38;5;124m"[39m[38;5;124mJapan[39m[38;5;124m"[39m][38;5;241m.[39mplot(ax[38;5;241m=[39max, legend[38;5;241m=[39m[38;5;28;01mTrue[39;00m, color[38;5;241m=[39memph_color, linewidth[38;5;241m=[39m[38;5;241m2.5[39m)
[0;32m----> 6[0m [43mdf[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mUnited Kingdom[39;49m[38;5;124;43m"[39;49m[43m][49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43max[49m[38;5;241;43m=[39;49m[43max[49m[43m,[49m[43m [49m[43mlegend[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mcolor[49m[38;5;241;43m=[39;49m[43msec_color[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m[43m [49m[43malpha[49m[38;5;241;43m=[39;49m[38;5;241;43m0.4[39;49m[43m,[49m[43m [49m[43mlinewidth[49m[38;5;241;43m=[39;49m[38;5;241;43m0.75[39;49m[43m)[49m
[1;32m      7[0m df[[38;5;124m"[39m[38;5;124mUnited States[39m[38;5;124m"[39m][38;5;241m.[39mplot(ax[38;5;241m=[39max, legend[38;5;241m=[39m[38;5;28;01mTrue[39;00m, color[38;5;241m=[39msec_color[[38;5;241m1[39m], alpha[38;5;241m=[39m[38;5;241m0.4[39m, linewidth[38;5;241m=[39m[38;5;241m0.75[39m)
[1;32m      8[0m df[[38;5;124m"[39m[38;5;124mChina[39m[38;5;124m"[39m][38;5;241m.[39mplot(ax[38;5;241m=[39max, legend[38;5;241m=[39m[38;5;28;01mTrue[39;00m, color[38;5;241m=[39msec_color[[38;5;241m2[39m], alpha[38;5;241m=[39m[38;5;241m0.4[39m, linewidth[38;5;241m=[39m[38;5;241m0.75[39m)

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_core.py:1000[0m, in [0;36mPlotAccessor.__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    997[0m             label_name [38;5;241m=[39m label_kw [38;5;129;01mor[39;00m data[38;5;241m.[39mcolumns
[1;32m    998[0m             data[38;5;241m.[39mcolumns [38;5;241m=[39m label_name
[0;32m-> 1000[0m [38;5;28;01mreturn[39;00m [43mplot_backend[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43mkind[49m[38;5;241;43m=[39;49m[43mkind[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_matplotlib/__init__.py:71[0m, in [0;36mplot[0;34m(data, kind, **kwargs)[0m
[1;32m     69[0m         kwargs[[38;5;124m"[39m[38;5;124max[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28mgetattr[39m(ax, [38;5;124m"[39m[38;5;124mleft_ax[39m[38;5;124m"[39m, ax)
[1;32m     70[0m plot_obj [38;5;241m=[39m PLOT_CLASSES[kind](data, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m---> 71[0m [43mplot_obj[49m[38;5;241;43m.[39;49m[43mgenerate[49m[43m([49m[43m)[49m
[1;32m     72[0m plot_obj[38;5;241m.[39mdraw()
[1;32m     73[0m [38;5;28;01mreturn[39;00m plot_obj[38;5;241m.[39mresult

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py:454[0m, in [0;36mMPLPlot.generate[0;34m(self)[0m
[1;32m    452[0m [38;5;28mself[39m[38;5;241m.[39m_make_plot()
[1;32m    453[0m [38;5;28mself[39m[38;5;241m.[39m_add_table()
[0;32m--> 454[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_legend[49m[43m([49m[43m)[49m
[1;32m    455[0m [38;5;28mself[39m[38;5;241m.[39m_adorn_subplots()
[1;32m    457[0m [38;5;28;01mfor[39;00m ax [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39maxes:

File [0;32m/usr/share/miniconda3/envs/lecture-datascience/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py:792[0m, in [0;36mMPLPlot._make_legend[0;34m(self)[0m
[1;32m    790[0m     title [38;5;241m=[39m leg[38;5;241m.[39mget_title()[38;5;241m.[39mget_text()
[1;32m    791[0m     [38;5;66;03m# Replace leg.LegendHandles because it misses marker info[39;00m
[0;32m--> 792[0m     handles [38;5;241m=[39m [43mleg[49m[38;5;241;43m.[39;49m[43mlegendHandles[49m
[1;32m    793[0m     labels [38;5;241m=[39m [x[38;5;241m.[39mget_text() [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m leg[38;5;241m.[39mget_texts()]
[1;32m    795[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mlegend:

[0;31mAttributeError[0m: 'Legend' object has no attribute 'legendHandles'

